version: '3.7'

services:
  database:
    image: mongo
    container_name: database
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - dbdata:/data/db
  cache:
    image: redis
    command: redis-server --requirepass ${CACHE_PASS}
    hostname: redis
    ports:
      - ${CACHE_PORT}:6379

volumes:
  dbdata:
    driver: local
