name: App Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.2]
        mongodb-version: [5.0]
        redis-version: [6]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
        env:
          CI: true

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run all test
        env:
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          API_KEY: ${{ secrets.API_KEY }}
          CACHE_PORT: ${{ secrets.CACHE_PORT }}
          CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
          CACHE_PASS: ${{ secrets.CACHE_PASS }}
        run: yarn test

      - name: Deploy App
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_TOKEN }}
          heroku_app_name: "beachforecast"
          heroku_email: "suares_silva.01@hotmail.com"

